name: Generate new image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: andy5995/slackware-build-essential:15.0

    steps:
      - name: Download SlackBuild
        run: wget --no-check-certificate -O- https://slackbuilds.org/slackbuilds/15.0/system/btop.tar.gz | tar -xz

      - name: Download btop source
        working-directory: btop
        run: |
          source ./btop.info && wget --no-check-certificate $DOWNLOAD
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Build Package
        working-directory: btop
        env:
          OUTPUT: /opt
          PKGTYPE: txz
        run: |
          chmod u+x btop.SlackBuild
          ./btop.SlackBuild

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: btop-${{ env.version }}-x86_64
          path: /opt/btop-*.txz
